apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-app-service-aks
spec:
  selector:
    app: multi-cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Exposes the service externally
